### ISSUE TITLE
hledger-ui : Quickly change status of an entry

### ISSUE THREAD

**Issue by SanAntonio37** [simonmichael/hledger#2182] opened 2024-03-08 06:22 UTC
Hi !

First of all, thank you for these worderful apps.

My wish is simple.
I'd like to change the status (marked/pending/cleared) of a journal entry directly from the hledger-ui interface.
I haven't found a key that can do this action.

Best regards.

**Comment by simonmichael** [comment] 2024-03-08 06:47
You're welcome! This is a duplicate of #632 and #1413, I'll close all but the first.

**Closed** 2024-03-08 06:47 UTC
Labels: duplicate, A-WISH, ui
