### ISSUE TITLE
hledger reports miss separator in random cells

### ISSUE THREAD

**Issue by ajrouvoet** [simonmichael/hledger#1662] opened 2021-08-21 14:00 UTC
In both `hledger cf --monthly` and `hledger is --monthly` I see multiple rows that randomly seem to miss the thousand separator.
Other entries in the same row/column do have the correct formatting. It is not so much restricted to those reports, as it is easier to spot the inconsistency there than in the non monthly reports.

I'm on Arch Linux. Pacman reports:

```
haskell-hledger-lib 1.21-29
hledger 1.21-30
```

I'd be happy to provide more information, but I'm unsure what is relevant info.

**Comment by Xitian9** [comment] 2021-08-22 00:27
Are you able to provide a minimal (non-)working example, without giving away private financial info?

**Comment by ajrouvoet** [comment] 2021-08-23 11:20
Must it be reproducible, or just a screenshot?

**Comment by Xitian9** [comment] 2021-08-23 11:44
Reproducible would be much more helpful, but a screenshot would be better than nothing. We might be able to diagnose the problem just from a screenshot, but if the problem is at all complicated we will probably need more information.

**Comment by ajrouvoet** [comment] 2021-08-23 11:49
I don't have time to make it reproducible right now, but it looks like this:

```
               || 0001-01-91  0001-00-08  0001-09-91  0001-03-90  0001-05-91  0001-06-90  0001-05-91  0001-08-91
===============++================================================================================================
 Assets        ||
---------------++------------------------------------------------------------------------------------------------
(...)
 assets:example|| €90.095,99  €91.509,50   €91809.99   €90110.01   €30005.58  €95.359,19   €98959.33   €31359.65
---------------++------------------------------------------------------------------------------------------------
               || €91.896,56  €99.191,90  €90.960,58  €96.605,09  €31.581,98  €30.009,15  €33.633,16  €33.509,38
===============++================================================================================================
(...)

```

**Comment by Xitian9** [comment] 2021-08-23 12:46
Yes, I can see. It looks like the commodity styles are not being made uniform in same cases (you'll notice that it's also using a full stop as a decimal point, rather than a comma). Unfortunately I can't really tell why that's being missed at present.

Can I ask if the entries are consistent in the journal, or are they sometimes entered in different styles? Are these numbers entered directly in the journal, or are they sometimes being auto-inferred (i.e. left blank), or being valued?

**Comment by ajrouvoet** [comment] 2021-08-23 12:53
Ah, yes this is an aggregate of multiple journals that are not entirely consistent (even internally). And some amounts are also auto-inferred.

**Comment by Xitian9** [comment] 2021-08-23 13:47
If you can get a reproducible example that would be very helpful.

**Comment by ajrouvoet** [comment] 2021-08-24 10:10
That looks like the same issue to me.

**Comment by ajrouvoet** [comment] 2021-08-24 10:36
The following steps fix the issue:
- Make the journals consistent
- Specify the commodity on top of each

If I leave out the commodity specification, the bug persists, suggesting that inferred amounts are in the wrong commodity style?

**Comment by Xitian9** [comment] 2021-08-24 11:03
Perhaps. Commodity styles are determined by all the amounts in a journal, and @la-wu's comment suggests that they are not unified across journals when using multiple -f arguments.

I think the best way of dealing with multiple journals is to have a single master journal which includes all the subjournals within it using include directives. You can then include commodity directives in the master file, and they'll automatically be included within all of them.

**Comment by la-wu** [comment] 2021-08-24 11:24
> I think the best way of dealing with multiple journals is to have a single master journal which includes all the subjournals within it using include directives.

Is there a reason we can't / don't treat multiple -f arguments as if it were written this way? The main thing that comes to mind is balance assertions / assignments no longer being isolated to a file-unit.

**Comment by Xitian9** [comment] 2021-08-24 12:14
> Is there a reason we can't / don't treat multiple -f arguments as if it were written this way? The main thing that comes to mind is balance assertions / assignments no longer being isolated to a file-unit.

I don't know. It seems like it should, but I haven't worked on this, so there may be a reason.

**Comment by simonmichael** [comment] 2021-08-24 14:32
@la-wu, each file is parsed separately, as they could come from different countries. And when any thousands (digit group) separators are present, it's important to declare the number format with a `commodity` directive for reliable parsing - cf https://hledger.org/hledger.html#decimal-marks-digit-group-marks

Multiple files are discussed at https://hledger.org/hledger.html#directives-and-multiple-files, it's pretty much the kind of thing you guessed. The https://hledger.org/hledger.html#directives table above gives the exact area of effect of the various directives.

**Comment by simonmichael** [comment] 2021-08-24 14:34
@ajrouvoet, thanks for the report. When you have time, it shouldn't be too hard to minimise your data - chop out as much as you can while still reproducing the bug. A repro will get this resolved quickly.

**Comment by simonmichael** [comment] 2021-08-24 14:41
Also, you might be able to check the current release (1.22.2) as well. (There's a static linux binary on the install page, eg.)

**Comment by simonmichael** [comment] 2021-09-21 01:18
@ajrouvoet any chance of a repro for this issue ? I'd like to explain it or fix it.

**Comment by simonmichael** [comment] 2023-06-24 05:05
Presumed fixed, closing.

**Closed by simonmichael** 2023-06-24 05:05 UTC
Labels: A BUG, journal
