### ISSUE TITLE
Don't write debug.log to $HOME when pressing `V` or `B` in hledger-ui.

### ISSUE THREAD

**Issue by crocket** [simonmichael/hledger#1556] opened 2021-05-08 12:49 UTC
There is no option to disable writing debug.log to $HOME when I press `V` or `B` in hledger-ui.

**Comment by simonmichael** [comment] 2021-05-14 21:40
hledger-1.21 was writing `./debug.log` when you press V, thanks for the report. This is fixed in master.

**Closed** 2021-05-14 21:41 UTC
Labels: A BUG, ui

**Comment by Xitian9** [comment] 2021-06-21 06:56
Sorry to resurect this, but there's another instance of this bug which arises when you press `g` in the transaction screen. I've put a PR for this in #1576.

**Comment by simonmichael** [comment] 2021-07-01 02:01
(Not actually a regression, the V key has being doing this since the feature was introduced.)
