### ISSUE TITLE
hledger-web: missing error when adding a transaction with an invalid date  [$20]

### ISSUE THREAD

**Issue by pangoSE** [simonmichael/hledger#433] opened 2016-11-20 22:04 UTC
The add-transaction-popup simply disappears with no changes to the journal being made requiring the user to type in everything again with a correct date.

**Comment by efx** [comment] 2017-12-09 13:37
I propose we make the date input a native date picker instead of the autocomplete one and use built in browser validation:
![151282707137324](https://user-images.githubusercontent.com/472721/33796100-1d6185ce-dcbc-11e7-993b-410259d05b37.png)
![151282700789673](https://user-images.githubusercontent.com/472721/33796101-1d6fad5c-dcbc-11e7-84a5-96f7ce8b4c72.png)
This would require a few extra styles on that date input, but would  otherwise provide an easily maintained fix.

**Comment by simonmichael** [comment] 2017-12-10 21:58
Perhaps this would be a full work around for the problem. And even though you'd lose the ability to enter hledger smart dates ("yesterday" etc.) it looks good. Pull requests welcome.

**Comment by simonmichael** [comment] 2018-10-05 03:36
Thanks, but I think the issue is still unsolved. Eg: at http://demo.hledger.org, press a, enter invalid date `1/2/3/4`, enter some description, press enter - the add form appears again without the description.

**Comment by nikhiljha** [comment] 2018-10-05 13:44
Or just `type="date" required` which does both of those things and some CSS. I'm working on this.

**Comment by efx** [comment] 2018-10-05 13:47
@nikhiljha we avoided `type="date"` before because of incompatibilities with Safari and some versions of IE; I don't know if the consensus has changed, but might be worth discussing in the IRC.

**Comment by nikhiljha** [comment] 2018-10-05 23:29
Opened a PR to discuss, but I'm also on IRC as fyber.

**Comment by simonmichael** [comment] 2018-10-06 01:30
We learned this [seems to be fixed](https://github.com/simonmichael/hledger/pull/886#issuecomment-427530586) by building with newer yesod libs (perhaps 1.6+). The form now works more conventionally and doesn't lose data. Closing.

**Closed by simonmichael** 2018-10-06 01:30 UTC
Labels: A BUG, bounty, web
