### ISSUE TITLE
roi: "Ratio has zero denominator" error

### ISSUE THREAD

**Issue by chrpinedo** [simonmichael/hledger#1796] opened 2021-12-28 17:22 UTC
I have been playing with the [return on investment cookbook](https://hledger.org/return-on-investment.html). I want roi for stocks with dividends and value appreciation. My setup is a bit more complex than the cookbook because I track some expenses such as commision and taxes.

Content of `bug.journal`:
```
2021-01-01 * buy shares
    assets:stocks  10 aapl @ 100.00 usd
    expenses:comissions  10.00 usd
    assets:checkings

2021-02-01 * dividends
    assets:stocks  0.00 usd
    assets:checkings  10.00 usd
    income:dividends

2021-03-1 * sell some stocks
    assets:stocks  -5 aapl @ 100.00 usd
    expenses:comissions  5.00 usd
    assets:checkings  505.00 usd
    income:pnl

P 2021-02-01 22:00:30 aapl 101.00 usd
P 2021-03-01 22:00:30 aapl 102.00 usd
P 2021-04-01 22:00:30 aapl 103.00 usd
```

When I run `hledger roi -f bug.journal --inv "assets:stocks" --pnl "expenses:|income:"  --value=then  --cashflow -e 2022.01.01` I get one error after IRR cash flows are reported:

```
IRR cash flow for 2021-01-01 - 2021-12-31
+------------++--------------+
|            ||       Amount |
+============++==============+
| 2021-01-01 || -1010.00 usd |
| 2021-02-01 ||    10.00 usd |
| 2021-03-01 ||   505.00 usd |
| 2022-01-01 ||   515.00 usd |
+------------++--------------+


TWR cash flow for 2021-01-01 - 2021-12-31
hledger: Ratio has zero denominator
```

So, it seems to be related to TWR cash flow calculation and the problem is with the first transaction named "buy shares" because if I skip it by beginning the report one day later, the error disappears (`hledger roi -f bug.journal --inv "assets:stocks" --pnl "expenses:|income:"  --value=then  --cashflow -b 2021.01.02 -e 2022.01.01`):

```
IRR cash flow for 2021-01-02 - 2021-12-31
+------------++--------------+
|            ||       Amount |
+============++==============+
| 2021-01-02 || -1010.00 usd |
| 2021-02-01 ||    10.00 usd |
| 2021-03-01 ||   505.00 usd |
| 2022-01-01 ||   515.00 usd |
+------------++--------------+


TWR cash flow for 2021-01-02 - 2021-12-31
+------------++-----------------+--------------++-----------+-------------+------------+-------++------------------+
|            || Portfolio value | Unit balance ||       Pnl |    Cashflow | Unit price | Units || New Unit Balance |
+============++=================+==============++===========+=============+============+=======++==================+
| 2021-01-02 ||            1010 |            0 || 10.00 usd | 1010.00 usd |        100 |  10.1 ||             10.1 |
| 2021-02-01 ||            1010 |         10.1 ||         0 |           0 |     100.99 |     0 ||             10.1 |
| 2021-02-01 ||            1020 |         10.1 ||  5.00 usd |  -10.00 usd |     100.99 | -0.10 ||            10.00 |
| 2021-03-01 ||            1020 |        10.00 ||         0 |           0 |     102.49 |     0 ||            10.00 |
| 2021-03-01 ||             515 |        10.00 ||         0 | -505.00 usd |     102.49 | -4.93 ||             5.07 |
| 2021-04-01 ||                 |              ||           |             |            |       ||                  |
+------------++-----------------+--------------++-----------+-------------+------------+-------++------------------+
Final unit price: 515.00 usd/5.07 units = 101.50
Total TWR: 1.50%.
Period: 1.00 years.
Annualized TWR: 1.50%

+---++------------+------------++---------------+-------------+-------------+-----------++-------+-------+
|   ||      Begin |        End || Value (begin) |    Cashflow | Value (end) |       PnL ||   IRR |   TWR |
+===++============+============++===============+=============+=============+===========++=======+=======+
| 1 || 2021-01-02 | 2021-12-31 ||   1010.00 usd | -515.00 usd |  515.00 usd | 20.00 usd || 3.47% | 1.50% |
+---++------------+------------++---------------+-------------+-------------+-----------++-------+-------+
``

My hledger version: `hledger 1.22.2, linux-x86_64`.

**Comment by adept** [comment] 2021-12-29 22:55
This can not be reproduced in master. 

This is a duplicate of #1682 and was fixed in, I think, 1.23

**Closed by adept** 2021-12-29 22:55 UTC
Labels: A BUG, roi
