### ISSUE TITLE
Automatic posting matches multiple unrelated currencies when using query cur:X

### ISSUE THREAD

**Issue by bcashlol** [simonmichael/hledger#1582] opened 2021-06-25 19:25 UTC
- Minimum reproducible example:

```
= cur:USD
  (b:USD)  *1

2017-12-14
  revenue:job  -10 EUR
  revenue:job  -10 USD
  assets
```

Output:

```
 hledger -f test.hledger print --auto
2017-12-14  ; modified:
    revenue:job         -10 EUR
    revenue:job         -10 USD
    (b:USD)             -10 USD  ; generated-posting: = cur:USD
    assets
    (b:USD)              10 EUR  ; generated-posting: = cur:USD
    (b:USD)              10 USD  ; generated-posting: = cur:USD
```

Notice this is creating an automatic posting for EUR, and also two automatic postings for USD. The expected behavior is a single automatic posting for only USD.

- The output of hledger --version
1.21

**Comment by bcashlol** [comment] 2021-06-25 19:37
Note this works as expected:

```
= revenue & cur:USD
  (b:USD)  *1

2017-12-14
  revenue:job  -10 EUR
  revenue:job  -10 USD
  assets  
```

Output:
```
hledger -f test.hledger print --auto
2017-12-14  ; modified:
    revenue:job         -10 EUR
    revenue:job         -10 USD
    (b:USD)             -10 USD  ; generated-posting: = revenue & cur:USD
    assets
```

But this does not work as expected:

```
= assets & cur:USD
  (b:USD)  *1

2017-12-14
  revenue:job  -10 EUR
  revenue:job  -10 USD
  assets  
```

Output:

```
hledger -f test.hledger print --auto
2017-12-14  ; modified:
    revenue:job         -10 EUR
    revenue:job         -10 USD
    assets
    (b:USD)              10 EUR  ; generated-posting: = assets & cur:USD
    (b:USD)              10 USD  ; generated-posting: = assets & cur:USD
```

Notice there are now two automatic postings on the inferred amounts, instead of just one as before.


If we do not use inferred amounts, it works as expected:
```
= assets & cur:USD
  (b:USD)  *1

2017-12-14
  revenue:job  10 EUR
  revenue:job  10 USD
  assets  -10 EUR
  assets  -10 USD
```

Output:
```
hledger -f test.hledger print --auto
2017-12-14  ; modified:
    revenue:job         -10 EUR
    revenue:job         -10 USD
    assets               10 EUR
    assets               10 USD
    (b:USD)              10 USD  ; generated-posting: = assets & cur:USD
```

**Comment by simonmichael** [comment] 2021-06-25 19:49
Thanks for the report @bcashlol. Just considering your first example, hledger is working as expected. Consider:
```
= cur:USD
  (b:USD)  *1

2017-12-14
  revenue:job  -10 EUR
  revenue:job  -10 USD
  assets
```
```
$ hledger print -x
2017-12-14
    revenue:job         -10 EUR
    revenue:job         -10 USD
    assets               10 EUR
    assets               10 USD
```
Your auto posting rule also matches the inferred balancing postings, you'll need to restrict it by account as well.

**Comment by bcashlol** [comment] 2021-06-25 20:14
@simonmichael Actually I already tried to address your example in my second comment. It is not working as expected, since it gives different results if you manually write out the postings versus let hledger infer the exact same postings.

Consider that these two examples I gave give two different outputs, even though using your logic, they should be the same:

```
= assets & cur:USD
  (b:USD)  *1

2017-12-14
  revenue:job  -10 EUR
  revenue:job  -10 USD
  assets  10 EUR
  assets  10 USD
```
The above gives a correct output.

```
= assets & cur:USD
  (b:USD)  *1

2017-12-14
  revenue:job  -10 EUR
  revenue:job  -10 USD
  assets
```
The above equivalent transaction gives an incorrect output (with an extra automatic posting for EUR). 

> you'll need to restrict it by account as well

Notice that in one of the above examples where we do restrict by account both EUR and USD are matched, but in the other only USD is matched. Regardless of whether we restrict by account, EUR should not be matched. Also notice in other examples where we do not match by account, EUR is matched in some cases when it should not be.

**Comment by simonmichael** [comment] 2021-06-25 20:24
Trying the examples in your latest comment, again I don't see a problem. Maybe I'm missing it. Can you show an actual repro (input, command, output with problem highlighted) ? Or if it's easier, come to [chat](https://hledger.org/#help).

Incidentally `&` is not part of hledger query syntax, and I'm surprised it doesn't seem to cause trouble.

**Comment by bcashlol** [comment] 2021-06-25 20:34
Yes, the same example from my 2nd comment:

Input:

```
= assets cur:USD
  (b:USD)  *1

2017-12-14
  revenue:job  -10 EUR
  revenue:job  -10 USD
  assets  
```

Output:

```
hledger -f test.hledger print --auto
2017-12-14  ; modified:
    revenue:job         -10 EUR
    revenue:job         -10 USD
    assets
    (b:USD)              10 EUR  ; generated-posting: = assets & cur:USD
    (b:USD)              10 USD  ; generated-posting: = assets & cur:USD
 ```

This auto generated posting is wrong:

```
 (b:USD)              10 EUR  ; generated-posting: = assets & cur:USD
 ```

The query is to match USD. This auto posting matched EUR!

**Comment by simonmichael** [comment] 2021-06-25 20:48
That did it. You're right, it's a bug. Good catch, thanks!

**Comment by Xitian9** [comment] 2021-06-28 05:32
I'm willing to bet this is due to an confusion I ran across when changing the internal representation of `MixedAmount`. I have a strong tendency to view the content of a `Posting` as an `Amount`, as it will always have just a single entry when read from the journal. However, it is actually a `MixedAmount`, and will sometimes have multiple entries when it's an auto posting. It's obvious to state, but easily forgotten when coding. My guess is some piece of code is checking whether a commodity is present in a `MixedAmount`, and then assuming all amounts in there have that commodity.

There is actually a fair amount of code which manually checks whether there is a single `Amount` in a `MixedAmount` and only works if there is. If we wanted to encode this in the type system, we could have `pamount :: Either Amount MixedAmount`, but this is probably more effort than it's worth.

**Comment by Xitian9** [comment] 2021-06-28 05:34
Yes, I'm betting the problem is here:
https://github.com/simonmichael/hledger/blob/eae4922d122dbc25a09a243a2f8e8b332c34dcd7/hledger-lib/Hledger/Query.hs#L560-L563

**Comment by simonmichael** [comment] 2021-06-28 08:01
You could be right, but it's not a regression, I think ? At least it didn't seem so to me, I tried some old versions.

**Comment by Xitian9** [comment] 2021-06-28 09:19
No, I don't think it's a regression. It's just a point that I frequently encountered and had to deal with: it wouldn't surprise me if it got missed earlier.

**Comment by simonmichael** [comment] 2021-07-01 20:28
Fixed by @Xitian9.

**Closed by simonmichael** 2021-07-01 20:28 UTC
Labels: A BUG, journal
