### ISSUE TITLE
Web: The query "(date:2020 )" causes Internal Server Error

### ISSUE THREAD

**Issue by thielema** [simonmichael/hledger#1245] opened 2020-05-25 09:21 UTC
Try this with hledger-web-1.17.99 from github-HEAD:
~~~~
http://localhost:5000/journal?q=(date%3A2020+)
~~~~
The space before the closing parenthesis causes the problem.
It seems that `parseQuery` is partial. I may try to fix that.

**Comment by simonmichael** [comment] 2020-05-25 17:10
Thanks for the bug report. I don't think parentheses are supported in queries, but you're right, it shouldn't crash.

**Comment by simonmichael** [comment] 2020-05-25 17:13
Oh, I suppose the parenthesised text gets parsed as a regular expression (with acct: prefix assumed). Yes:
```
$ hledger print "(date:2020 )" --debug=2
...
query from opts & args: Acct "(date:2020 )"
...
$ (no error)
```

**Comment by amigalemming** [comment] 2020-07-30 06:48
What would be the proposed way to report the error?
Show a read parser error message below the query field?
Show the unfiltered journal? Show an empty query result?

**Comment by simonmichael** [comment] 2020-07-31 00:09
@amigalemming good question, I am guessing the usual way hledger-web shows errors - try adding an unbalanced transaction to see it.

Reading this again though I'm not sure why it should be an error, hledger-web should interpret this as a valid regular expression, matching an account name, as hledger does above.

**Comment by simonmichael** [comment] 2020-07-31 00:11
PS we're not sure if the UI allowed the user to create this situation unintentionally, that would be a separate issue. I'm assuming a url typed manually.

**Comment by amigalemming** [comment] 2020-07-31 09:56
I see we are discussing two issues: The particular parse error and the parse error causing an Internal Server Error. I like to open two new issues and close this one.

**Comment by amigalemming** [comment] 2020-07-31 10:13
Hm, I hesitate to phrase an issue for the parser error. On the one hand I find the parser result surprising, on the other hand it seems to be intended behaviour.

**Comment by amigalemming** [comment] 2020-08-01 09:24
I hope this can be resolved by #1315.

**Comment by simonmichael** [comment] 2020-08-04 16:13
I'll keep this open until the actual issue is fixed (repro: paste `(date:2020 )` into hledger-web search field and hit enter -> internal server error).

**Comment by Xitian9** [comment] 2021-04-04 00:03
I think this issue can be closed. We currently get a ‘regex cannot be compiled’ message rather than an internal server error.

**Closed** 2021-04-04 00:06 UTC
Labels: A BUG, web
