### ISSUE TITLE
Invalid amount format (Windows)

### ISSUE THREAD

**Issue by w1ld** [simonmichael/hledger#545] opened 2017-05-09 07:56 UTC
Seems to be a bug. Or does hledger disregard amount format in `commodity` directive?

File "mytest.ledger": 

```
commodity р 10,000.0 

2016/06/08 * My transaction
    Cash
    Bank                                                р 20,000
```

Under cygwin (locale LANG=ru_RU.UTF-8) and under powershell (chcp 65001)
```
$ hledger.exe -f hledger_decimal_point_test.ledger r
2016/06/08 My transaction       Cash                      р -20.0      р -20.0
                                Bank                       р 20.0             0
```

And for this:
```
commodity р 10,000.0 

2016/06/08 * My transaction
    Cash
    Bank                                                р 20,000.00
```

It gets:
```
$ hledger.exe -f hledger_decimal_point_test.ledger r
2016/06/08 My transaction       Cash                  р -20,000.0  р -20,000.0
                                Bank                   р 20,000.0             0
```

hledger 1.2, Windows 10

**Comment by ony** [comment] 2017-05-14 17:43
This looks like a duplicate of #487 .
Right now work around is always use decimals if you use digits groups separator. This is not related to locale.
Problem is that parsing done regardless of any format specification. Actually you get format from parsed amount. Parser is pretty simple and decides that decimal part separator is the last one, as I remember.

**Comment by w1ld** [comment] 2017-08-26 16:37
Just to let know that it reproduced under 1.3.99 with compiled exe (taken [here](https://ci.appveyor.com/project/simonmichael/hledger/build/artifacts))

```
> cat .\mytest.ledger
commodity СЂ 10,000.0

2016/06/08 * My transaction
    Cash
    Bank                                                СЂ 20,000

> chcp
Active code page: 65001

> .\hledger.exe -f .\mytest.ledger r
2016/06/08 My transaction       Cash                       р -20.0       р -20.0
                                Bank                        р 20.0             0

> .\hledger.exe --version
hledger 1.3.99
```

**Comment by ony** [comment] 2017-08-27 19:00
@w1ld it looks like #487 is still open. You may want to track that issue instead.

@simonmichael does it makes sense to close this one as duplicate of #487 ?

**Comment by simonmichael** [comment] 2017-08-27 19:42
Sounds good to me, thanks.

**Closed by simonmichael** 2017-08-27 19:42 UTC
Labels: A BUG, docs, journal
