### ISSUE TITLE
Clear transactions directly in hledger-ui

### ISSUE THREAD

**Issue by a-zurcher** [simonmichael/hledger#1413] opened 2020-12-13 23:00 UTC
Suggestion:  adding a shortcut to clear transactions directly directly into hledger-ui
the cleared symbol (*) would imo make the most sense as shortcut

Additionally, after having an entry, the next transaction could be automatically selected in order to go quicker when clearing a lot of transactions

**Comment by simonmichael** [comment] 2020-12-13 23:46
Agreed! Changes like require a tricky internal enhancement, which is doable but non-trivial: a robust subsystem for safely modifying parts of journal files, without losing the user's data.

**Comment by simonmichael** [comment] 2024-03-08 06:47
A duplicate of #632, I'll close this one.

**Closed by simonmichael** 2024-03-08 06:47 UTC
Labels: A-WISH, ui
