### ISSUE TITLE
Calculated Balance Assertions

### ISSUE THREAD

**Issue by JP-Ellis** [simonmichael/hledger#923] opened 2018-11-01 01:26 UTC
In `ledger`, it is possible to use calculated values for balance assertions, for example:

```
2018-10-30 * Interest
    Assets:Currency:Bank                             AUD 5.00 = (AUD 200.00 + AUD 1,000.00)
    Income:Interest
```
which is useful if you have tightly linked accounts.  When `hledger` tries to parse the file, it raises the error:

```
/home/josh/Finance/finance.ledger:
    |
xxx |     Assets:Currency:Bank                             AUD 5.00 = (AUD 200.00 + AUD 1,000.00)
    |                                                                             ^
unexpected '+'
expecting ';', '{', end of input, newline, or the rest of amount (for a balance assertion or assignment)
```
Is this expected behaviour from `hledger`?  Or should this be allowed?

**Comment by simonmichael** [comment] 2018-11-01 01:37
This is expected, we don't support those kind of amount expressions. We are thinking about adding them though, see #871 and related PRs.

**Comment by simonmichael** [comment] 2018-11-01 01:39
Related to that, it would be quite useful to hear more details about real-world use cases where this feature is valuable ("tightly linked accounts" ?)

**Comment by JP-Ellis** [comment] 2018-11-01 01:57
I think it would be a really nice feature to have.

----

As for the particular real-world use case, here's my situation; I have a bank which provides me with two accounts:

- A transaction account with no interest, but with a debit card; and,
- A savings account with high interest, but no debit card.

Every night, money is automatically taken out from the savings account and placed in the transaction account in order to maintain a minimum account balance.  I'll also occasionally make manual transfers between these two accounts if I wish to make a larger purchase.  As a result, I have a lot of transactions between these two account which I don't really want to keep track of and I really want to treat them as just the one account.

**Comment by simonmichael** [comment] 2018-11-01 04:16
Thanks for the example. Why are amount expressions useful in this case ?

**Comment by JP-Ellis** [comment] 2018-11-01 04:34
Furthermore, I can think of one other use-case for having balance assertions in the context of cryptocurrencies.

Specifically, some cryptocurrencies (prefer to) use addresses only once (the sequence addresses are generated according to a seed).  This means every time a transaction takes place, the source address is completely emptied and new addresses are created to store the change.

Here's an example:

```
2018-01-01 * Receive Money
    ; Paid to address 0x1
    ; Balance 0x1: 100
    Assets:Crypto                                          100
    Income:Gifts

2018-01-02 * Receive Money
    ; Paid to address 0x2
    ; Balance 0x1: 100
    ; Balance 0x2: 200
    Assets:Crypto                                          200
    Income:Gifts

2018-01-03 * Give Money
    ; Taken from address 0x1, remaining 70 put into 0x3
    ; Balance 0x1:   0
    ; Balance 0x2: 200
    ; Balance 0x3:  70
    Expenses:Gifts                                          30
    Assets:Crypto

2018-01-04 * Receive Money
    ; Paid to address 0x4
    ; Balance 0x1:   0
    ; Balance 0x2: 200
    ; Balance 0x3:  70
    ; Balance 0x4: 300
    Assets:Crypto                                          300
    Income:Gifts

2018-01-05 * Give Money
    ; Taken from address 0x2, 0x3 and 0x4 remainder placed into 0x5
    ; Balance 0x1:   0
    ; Balance 0x2:   0
    ; Balance 0x3:   0
    ; Balance 0x4:   0
    ; Balance 0x5:  20
    Expenses:Gifts                                         550
    Assets:Crypto
```

Generally, the clients that manage these transactions will automatically sum up the balances of all the owned addresses, but this still gives a good example of "tightly linked accounts".

**Comment by simonmichael** [comment] 2018-11-01 15:20
Thanks! I think I got the first one. I haven't yet got the second one. I would say I'm not yet seeing significant pain being caused by not having this feature. Nevertheless, it seems quite possible that we may have it soon. I'll close this in favour of #871.

**Closed by simonmichael** 2018-11-01 15:20 UTC
Labels: A WISH, journal
