### ISSUE TITLE
TWR aggregation looks wrong

### ISSUE THREAD

**Issue by TPolzer** [simonmichael/hledger#2298] opened 2024-12-10 21:44 UTC
I was trying to plot cumulative TWR values from hledger over time (side note: is there a machine readable version of `roi`?), but couldn't make sense of the numbers. In the end I've come to the conclusion that something isn't right.

Here's an example ledger that demonstrates the problem:
```
D 1,000.00 EUR 

2018-07-01 investment
        assets:bank
        investments:iShares Core MSCI World     1 "IE00B4L5Y983"

P 2018-12-28 "IE00B4L5Y983" 43.11000000 "EUR"
P 2019-06-28 "IE00B4L5Y983" 50.93000000 "EUR"

2019-07-01 investment
        assets:bank    
        investments:iShares Core MSCI World     10 "IE00B4L5Y983"

P 2019-12-30 "IE00B4L5Y983" 56.59000000 "EUR"
```
Following https://hledger.org/roi.html#using-commodities-and-prices I get this report:
```
$ hledger roi --value then --begin 2019 --end 2020 --inv investmen --pnl '"profit and loss"' -p 'every 2 quarters'
+-------++------------+------------++---------------+------------+-------------+-----------++--------++------------+----------+
|       ||      Begin |        End || Value (begin) |   Cashflow | Value (end) |       PnL ||    IRR || TWR/period | TWR/year |
+=======++============+============++===============+============+=============+===========++========++============+==========+
|     1 || 2019-01-01 | 2019-06-30 ||     43.11 EUR |          0 |   50.93 EUR |  7.82 EUR || 39.96% ||     18.14% |   39.96% |
|     2 || 2019-07-01 | 2019-12-31 ||     50.93 EUR | 509.30 EUR |  622.49 EUR | 62.26 EUR || 23.25% ||     11.11% |   23.24% |
+-------++------------+------------++---------------+------------+-------------+-----------++--------++------------+----------+
| Total || 2019-01-01 | 2019-12-31 ||     43.11 EUR | 509.30 EUR |  622.49 EUR | 70.08 EUR || 24.51% ||     12.69% |   12.69% |
+-------++------------+------------++---------------+------------+-------------+-----------++--------++------------+----------+
```
My hand calculations for TWR would be:
- 2019-01-01 to 2019-06-30: no cashflow, price moved from 43.11 to 50.93 => 18.14% TWR/period
- 2019-07-01 to 2019-12-31: cashflow immediately at the begin, afterwards appreciation from 50.93 to 56.59 => 11.11% TWR/period
- Total TWR over the year should simply be the appreciation of IE00B4L5Y983 over the period (since the portfolio composition didn't change, only the size did): 56.59/43.11 => **31.27%**. That doesn't match what the `Total` row of the report says.
- Using `hledger roi -Y` is consistent with the `Total` above, not with the expected TWR.

**Comment by adept** [comment] 2024-12-11 21:17
To give you a quick feedback: thank you for your report, this is a bug, I see where it is, expect a fix soon.
(TWR incorrectly updates internal unit price)

**Comment by adept** [comment] 2024-12-11 22:37
Should be fixed by #2300

**Comment by TPolzer** [comment] 2024-12-11 23:19
Thank you for the quick reaction and fix! I can confirm that the numbers with #2300 look much better.

Unfortunately the proposed fix also makes my yearly ROI report 7-8x slower. That's better than wrong data, but somewhat painful.

**Comment by adept** [comment] 2024-12-12 18:53
> Unfortunately the proposed fix also makes my yearly ROI report 7-8x slower

I do see slowdown, but not as drastic as you.

Trying my dataset:
```
v1.32.99 :  13.5-14s
v1.40 : 14-14.5s
v1.41.99 (current HEAD) : 15s
v1.41.99+#2300 : 25s
```

This is ... weird. I'll try and see why it is so slow, change certainly does not look like something that should have a pronounced effect

**Comment by adept** [comment] 2024-12-12 19:47
@TPolzer i've pushed something into #2300 that should hopefully lead to more sharing of intermediate results and recover some of the lost performance. Can you please see how this behaves for you?

**Comment by TPolzer** [comment] 2024-12-12 20:42
Tried it just now, I don't see a significant change in performance, it's still pretty slow.

Trying with a subset of my roi query and some debug output:
old:
```
$ time hledger roi [...] --value then,CHF --begin 2018 --end tomorrow -Y --debug=2 |& grep seeking | sort | uniq -c
     15 seeking EUR to CHF price using forward prices
      9 seeking IE00B4L5Y983 to CHF price using forward prices
[...]

real	0m0.760s
user	0m0.731s
sys	0m0.035s
```
vs. new:
```
$ time hledger roi [...] --value then,CHF --begin 2018 --end tomorrow -Y --debug=2 |& grep seeking | sort | uniq -c
     15 seeking EUR to CHF price using forward prices
   2154 seeking IE00B4L5Y983 to CHF price using forward prices
[...]

real	0m15.982s
user	0m15.246s
sys	0m0.863s
```

The 15 EUR lookups are cashflow (in EUR) transactions I think, and they're the same. It should need the "IE00B4L5Y983 to CHF" chain only at period boundaries and cashflow events, too?

**Comment by adept** [comment] 2024-12-12 21:06
and ond dates you have P directives too (which was not happening earlier)

**Comment by TPolzer** [comment] 2024-12-12 21:19
Yeah... that explains the dramatic difference in runtime, since I have a large automatically created list of prices.

But that's not actually necessary, is it? To compute TWR it's sufficient to compute prices at period boundaries and cashflow events. E.g. in the initial example on this bug, inserting a lot of fine grained P directives would not change the result at all.

**Comment by adept** [comment] 2024-12-12 21:45
Just to double-check, in the example above is "old" a v1.40, or v1.41.99 without #2300?

**Comment by TPolzer** [comment] 2024-12-12 21:55
"old" is actually 1.32.3 from Debian.

**Comment by simonmichael** [comment] 2024-12-12 22:25
How many P directives have you @TPolzer ? I'm thinking we might need to mention that in general docs.

**Comment by TPolzer** [comment] 2024-12-12 22:31
I'm storing daily FX rates for three currencies and weekly rates for a handful of investments. I should probably reduce the latter to monthly rates. My current auto generated price list has ~21k entries.

I understand that general parsing etc scales linearly, but I was under the impression (so far I think correctly) that most analysis cost should be unaffected by the number of P statements.

**Comment by simonmichael** [comment] 2024-12-12 23:33
It's good to know the number. If you're seeing no slowdowns in most features, with 20k prices, that's good - perhaps it's something suboptimal in roi then.

**Comment by adept** [comment] 2024-12-13 20:38
I think you are both right, but I'll need a bit of time to think about it

**Comment by adept** [comment] 2024-12-16 18:26
Original code for roi was written ages ago when the current `value` framework was just not there. And indeed it looks like the code could be simplified (a lot) which I attempted to do, and re-pushed to #2300 .

@TPolzer if you have time to give it another spin, I would be curious how it works for you and your thousands of prices :)

**Comment by TPolzer** [comment] 2024-12-17 18:02
I built from d04e76711dfdf61c09b3be911873a0d5cf64f129, it seems it's still querying prices proportional to the number of P directives.

**Comment by adept** [comment] 2024-12-17 21:06
if you run it with --cashflow, it will show you all the entries it wants to process to compute TWR. It would call `mixedAmountApplyValuation` (which is the thing that needs P directives) exactly once per entry  (this is new), plus it will apply it to all cashflow/pnl postings as well (this is not new, and was not changed since roughly 1.33). 

So any additional suboptimal/excessive work, if it still exists, might be inside `mixedAmountApplyValuation`, I think.

What about raw runtime? I do not see any changes on my dataset with https://github.com/simonmichael/hledger/commit/d04e76711dfdf61c09b3be911873a0d5cf64f129

Sorry for the stupid questions, but I must admit that this feedback is perplexing: I see how previously there would be as many `mixedAmountApplyValuation` calls as there were P directives (and I was able to reproduce it locally), but it simply should not be the case anymore (and this I can also observe locally), so would it be ok for me to ask you to double-check your findings, in particular `hledger --version`, which should be `hledger 1.41.99-gd04e76711-20241216`?

Can you please repeat your debug run with

```
hledger roi .... --debug 3 2>&1 | grep seeking -B2 | grep "valuation date" | uniq -c
```
and see how many unique dates you get, and whether there are any dates there on which you dont have any investment-related transactions?

**Comment by TPolzer** [comment] 2024-12-17 23:07
To make this a bit more reproducible, I've added some nonsense (i.e. not change at all to the expected report) intermediate prices to the initial example, here's my current test journal: https://gist.github.com/TPolzer/0176eda7b6b0560e0ac77a4bf513cbfb

With hledger 1.41.99-gd04e76711-20241216, linux-x86_64:
```
$ time hledger roi --value then --begin 2019 --end 2020 --inv investmen --pnl '"profit and loss"' -p 'every 2 quarters' --debug 3 2>&1 | grep seeking -B2 | grep -o "valuation date: ....-.." | uniq -c
      1 valuation date: 2019-01
      1 valuation date: 2019-07
      1 valuation date: 2020-01
     30 valuation date: 2019-01
     28 valuation date: 2019-02
     31 valuation date: 2019-03
     30 valuation date: 2019-04
     31 valuation date: 2019-05
     28 valuation date: 2019-06
     30 valuation date: 2019-07
     31 valuation date: 2019-08
     30 valuation date: 2019-09
     31 valuation date: 2019-10
     30 valuation date: 2019-11
     30 valuation date: 2019-12

real	0m0.348s
user	0m0.297s
sys	0m0.073s
```
hledger 1.32.3, linux-x86_64:
```
$ time hledger roi --value then --begin 2019 --end 2020 --inv investmen --pnl '"profit and loss"' -p 'every 2 quarters' --debug 3 2>&1 | grep seeking -B2 | 
grep -o "valuation date: ....-.." | uniq -c
      1 valuation date: 2019-01
      1 valuation date: 2019-07
      1 valuation date: 2020-01

real	0m0.141s
user	0m0.115s
sys	0m0.033s
```

**Comment by TPolzer** [comment] 2024-12-18 13:38
Apologies, it seems between applying pull requests, I somehow messed up my git, I was not building from a clean checkout.

It looks much better now, indeed. My roi query on my large personal database is still slightly slower than at 1.32.3, but very acceptable at ~3% slowdown.

Thank you!

**Comment by simonmichael** [comment] 2024-12-18 16:57
Hurrah, thank you both. I’ll merge soon, if  nothing else is needed. 

In the past I thought of adding a “dirty working copy” indication to —version output - I guess this would have been helpful here!

**Comment by adept** [comment] 2024-12-18 16:57
I am glad we got to the bottom of it.

Thank you for all the testing/double-checking efforts here!

@simonmichael #2300 is ready to be merged whenever, I think

**Closed** 2024-12-18 17:42 UTC
Labels: A-BUG, roi, valuation
