### ISSUE TITLE
web: register: chart breaks with multiple commodities & transaction prices, showing nothing (since 1.22)

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1597] opened 2021-07-08 23:06 UTC
In hledger-web 1.22's register screen, when viewing an account containing multiple commodities with transaction prices, chart data can be misformatted (due to multiline amount rendering ?) causing a javascript error.

**Comment by Xitian9** [comment] 2021-07-09 03:31
Git bisect seems to show that this broke with the merging of the haskellerz talk notes. I can't tell precisely which commit because there are no stack files within the branch that was merged.

**Comment by Xitian9** [comment] 2021-07-09 03:49
Correction: it seems to break with commit 5e7b6935, where the internal representation of `MixedAmount` changed. This makes much more sense.

**Comment by simonmichael** [comment] 2021-07-09 03:54
Thanks! Here's a repro (viewing the x account):
```
commodity $ 0.00
commodity A 0.000000

2021-02-02
    (x:a)                                       A -0.173025 @ $0.499537 
    (x:b)                                        A 0.173025 @ $0.401414
    (x:c)                                         $0.016
```

**Comment by Xitian9** [comment] 2021-07-09 05:52
Found it. Prices were not being properly stripped, and so it was trying to render on more than one line.

**Comment by simonmichael** [comment] 2021-07-10 04:37
Merged, thanks for the quick fix.

**Comment by simonmichael** [comment] 2021-07-10 04:52
I think there's still a problem, either this issue or another. Compare the chart for the above example with hledger-web 1.21. With master (which now includes f3f821b), it's different. The blue A point is being plotted at ~0.17, even though the tooltip correctly says it is 0.

**Comment by simonmichael** [comment] 2021-07-10 04:56
20 minute rule - I'm going to unpush that commit from master to take the pressure off, please excuse the disruption.

**Comment by simonmichael** [comment] 2021-07-10 05:01
Here's another request, for the commit message: fix: is good, and since that denotes an end-user visible change, let's write (at least the first part of) the text for end users, ready for release notes. Maybe "fix: web: register chart with multiple commodities/prices, broken in 1.22 (#1597)" or something like that.

**Comment by Xitian9** [comment] 2021-07-10 05:51
Noted. I'll look into this and see what the problem is.

**Comment by Xitian9** [comment] 2021-07-10 05:52
Ah yes, prices are still not being stripped properly. They're now stripped for the display, but not for the plotting. I'll fix that shortly.

**Comment by simonmichael** [comment] 2021-07-10 06:26
This brings up the "how would we test for such bugs" and as usual with UIs it's a bit awkward. The best I can think of right now is run selenium tests and check for JS errors.

**Closed** 2021-07-13 05:09 UTC
Labels: A BUG, bounty, regression!, release needed, web
