### ISSUE TITLE
hledger-web --base-url has no effect in 1.32

### ISSUE THREAD

**Issue by rajeevn1** [simonmichael/hledger#2127] opened 2023-12-07 21:53 UTC
the option works in 1.31

**Comment by simonmichael** [comment] 2023-12-07 21:58
Thanks for the report. What's a good way to demonstrate the bug ? 

@klockeph if you have some time maybe you could take a look and see if this is fallout from #2100 ?

**Comment by simonmichael** [comment] 2023-12-15 01:43
@rajeevn1 I can't reproduce here on a mac; are you on GNU/linux ?

```
$ hledger-web-1.32.1 -f examples/sample.journal --socket a.sock
...
```
```
$ curl --unix-socket a.sock http://localhost/version
"1.32.1"~/src/hledger$ curl -i http://localhost:5000/version
HTTP/1.1 403 Forbidden
Content-Length: 0
Server: AirTunes/745.13.4

```

**Comment by rajeevn1** [comment] 2023-12-15 02:13
Yes I am on debian stable

**Comment by simonmichael** [comment] 2023-12-15 03:02
Hmm, ubuntu should be similar but I still can't reproduce there:
```
# bin/hledger-web-1.32.1 --socket sock -f examples/sample.journal
14/Dec/2023:17:00:26 -1000 [Info#yesod-core] Application launched @(yesod-core-1.6.25.1-2476c48f8d67ca7e46d176d339df66dc378a0de5bfbaae5a5cb02098f201a4f1:Yesod.Core.Dispatch src/\
Yesod/Core/Dispatch.hs:188:10)
Serving web UI and API on 127.0.0.1:5000 with base url http://127.0.0.1:5000
Press ctrl-c to quit
```
```
# curl -i http://127.0.0.1:5000
curl: (7) Failed to connect to 127.0.0.1 port 5000 after 0 ms: Connection refused
```

**Comment by simonmichael** [comment] 2023-12-15 03:03
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.10
Release:        22.10
Codename:       kinetic
```

**Comment by rajeevn1** [comment] 2023-12-15 14:14
I am trying to run it behind apache reverse proxy, which works for 1.31 but not for 1.32.

ProxyPass /hledger/ unix:/<path>/hledger.sock|http://127.0.0.1:5000/
ProxyPassReverse /hledger/ unix:/<path>/hledger.sock|http://127.0.0.1:5000/

I will check if I can find more info.

**Comment by simonmichael** [comment] 2023-12-15 15:18
Could you also test with curl, just to simplify ? See if you can produce a transcript like mine above, with 1.31 and 1.32.1.

**Comment by rajeevn1** [comment] 2023-12-15 15:21
I tried that already, curl works.

**Comment by simonmichael** [comment] 2023-12-15 15:23
For clarity, could you show a transcripts ? When you have time. I don't know what works means.

**Comment by rajeevn1** [comment] 2023-12-15 15:29
```
curl -q -v --unix-socket sock http://127.0.0.1:5000/version
*   Trying sock:0...
* Connected to 127.0.0.1 (sock) port 5000 (#0)
> GET /version HTTP/1.1
> Host: 127.0.0.1:5000
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Fri, 15 Dec 2023 14:19:22 GMT
< Server: Warp/3.3.31
< Content-Length: 8
< Content-Type: application/json; charset=utf-8
< Vary: Accept-Encoding, Accept, Accept-Language
< 
* Connection #0 to host 127.0.0.1 left intact
"1.32.1"
```

**Comment by simonmichael** [comment] 2023-12-15 15:32
I was hoping for full transcripts like mine, but never mind. Make sure you don't have an old instance still running on port 5000.

**Comment by simonmichael** [comment] 2023-12-15 15:38
Ah.. @rajeevn1 your command above is using the socket file and working as expected. Please show curl without --unix-socket also.

**Comment by simonmichael** [comment] 2023-12-15 15:40
As in https://github.com/simonmichael/hledger/issues/2127#issuecomment-1857137159

**Comment by rajeevn1** [comment] 2023-12-15 15:48
I think the problem with 1.32 is that it is not handling --base-url=BASEURL correctly, and still redirecting to http://127.0.0.1:5000.  I will check more when I have some time.

**Comment by simonmichael** [comment] 2023-12-15 16:19
While testing I did notice that hyperlinks didn't seem to be respecting --base-url. And you're right, that seems to be what has broken in 1.32. Thanks !

**Comment by simonmichael** [comment] 2023-12-15 21:18
@klockeph Hi, this is indeed fallout from your #2100. Adding guessApprootOr breaks --base-url when people are using that (I guess you are not ?). How could we satisfy both cases ?

**Comment by simonmichael** [comment] 2023-12-15 21:22
I guess use guessApprootOr only when --base-url option is not used ?

**Comment by klockeph** [comment] 2023-12-15 21:23
Oh nooo.... Sorry for that! I'm indeed not using this option.

I think what I described in https://github.com/simonmichael/hledger/pull/2100#issuecomment-1765312900 could be a viable alternative.

Edit: you were faster than me. yes using guessAppRoot only when --base-url option is not used is probably the way to go :)

**Comment by simonmichael** [comment] 2023-12-15 21:39
Unfortunately it seems to be a compile-time configuration: https://hackage.haskell.org/package/yesod-core-1.6.25.1/docs/Yesod-Core.html#v:approot

**Comment by klockeph** [comment] 2023-12-15 21:43
ooof. In that case, should we rather find out why `guessApproot` guesses a wrong approot for the specific request?

**Comment by simonmichael** [comment] 2023-12-15 23:51
My test was like:
```
$ hledger-web -f/dev/null --serve --base-url http://BASE
```
Good:
```
$ curl -s http://localhost:5000/journal | rg '(href)="\w.*?"' -o
href="http://BASE/static/css/bootstrap.min.css"
href="http://BASE/static/css/bootstrap-datepicker.standalone.min.css"
href="http://BASE/static/hledger.css"
href="http://BASE/journal"
```
Bad (with guessAppRootOr):
```
$ curl -s http://localhost:5000/journal | rg '(href)="\w.*?"' -o
href="http://localhost:5000/static/css/bootstrap.min.css"
href="http://localhost:5000/static/css/bootstrap-datepicker.standalone.min.css"
href="http://localhost:5000/static/hledger.css"
href="http://localhost:5000/journal"
```
I didn't think that guessApproot could be expected to guess right in all cases, maybe it could but doesn't here.

I tried hard but haven't been able to implement both cases today, which means I must revert #2100 unfortunately.

**Comment by simonmichael** [comment] 2023-12-16 00:04
This is fixed in master, and a bugfix release will follow at some point. @rajeevn1 thanks for the report, claim your https://hledger.org/REGRESSIONS.html#regression-bounty when convenient.

**Closed by simonmichael** 2023-12-16 00:04 UTC
Labels: A BUG, web, release-needed, regression!, severity4, impact3

**Comment by rajeevn1** [comment] 2023-12-16 02:29
submitted invoice for regression bounty, thanks!!
