### ISSUE TITLE
roi gives unclear "No solution -- not bracketed" error

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1398] opened 2020-11-17 21:58 UTC
A user on #hledger is getting this error and we don't know why, even though we traced it to "The result of searching for a root of a mathematical function.: The function does not have opposite signs when evaluated at the lower and upper bounds of the search." in the math-functions package. `roi` should make this error (and the others) impossible, or explain them well enough for new hledger users and non-math/investment-experts to understand (or at least, to fix).

**Comment by adept** [comment] 2020-11-18 00:21
It would be nice to have a reproducible example.

For  IRR part of roi, it tries to solve an equation to find a constant rate of return `r` such that investment (taking into account all cash flows) grows with rate `r` and reaches the same final balance that it actually has. The error likely means that this equation is not solvable. Perhaps final balance is negative, cashflow does not make sense, or some other corner case is hit.

That being said, error message could definitely be better. The problem is that it is hard to guess the exact root cause here

**Comment by simonmichael** [comment] 2020-11-18 02:26
Keeping this open for a little more exploration.

**Comment by simonmichael** [comment] 2020-11-21 00:32
We have [documented](https://hledger.org/hledger.html#roi) these errors. We don't yet prevent them (if it's possible) or provide any advice on how to resolve them. I'll keep this issue open until that improves.

**Comment by psamim** [comment] 2020-11-21 09:50
@simonmichael Thanks for opening this issue. There was an error in my ledger entries. This is an example of a ledger file which cause the same problem. The mistake was mine but maybe there could be better errors or maybe I was not knowledgeable enough to understand the error.

The mistake is in the entry for the date 2020-12-31, the last line is `Assets:Cash     -10 A @ 120` but it should be `Assets:Cash     10 A @ 120`.

```ledger
2019-11-30
    Assets:V       5 A @ 100
    Equities

2020-12-02
    Assets:V       5 A @ 120
    Equities

2020-12-31
    Income
    Assets:V         -5 A @ 100
    Assets:V         -5 A @ 120
    Assets:Cash     -10 A @ 120

2021-01-01
    Income
    Assets:V         10 A @ 100
    Assets:Cash           -1200

```

**Comment by simonmichael** [comment] 2021-01-13 19:08
@psamim, what command reproduces this error with your example above ? I'd like to check it with latest master and 1.20-branch.

**Comment by psamim** [comment] 2021-01-19 19:40
@simonmichael I tested it with 1.20 branch, It gives a very nice error message with explanation about possible causes. Thanks! I think we can close this.

**Closed** 2021-01-19 19:42 UTC
Labels: A BUG, docs, roi
