### ISSUE TITLE
regression 1.22: cur:/amt: now match after valuation, not before

### ISSUE THREAD

**Issue by julian-klode** [simonmichael/hledger#1625] opened 2021-07-23 07:27 UTC
I'm trying to figure out how much I hold in a given currency, in my normal currency. This used to work in 1.21, but stopped working in 1.22 (using the docker images atm) - it now always produces 0.

For the given test.journal:
```
P 2021/07/23 test 50€

2021/07/23 buy 10 test
    assets   10 test
    income  -50€
```

Which value you use for `--value` does not matter, fwiw, well I tried `now`, `cost`, `end`.

```
$ hledger -f $PWD/test.journal  bal --value=now cur:test
--------------------
                   0  
$ hledger-1.21 -f $PWD/test.journal  bal --value=now cur:test
                500€  assets
--------------------
                500€  
$ hledger-1.21 -f $PWD/test.journal  bal 
             10 test  assets
                -50€  income
--------------------
             10 test
                -50€  
```

**Comment by Xitian9** [comment] 2021-07-23 07:36
Hmm. I believe the question is whether we should match currencies before valuation or after valuation. Based on this report, it looks like we used to match before valuation, and now match after.

I would actually expect to match after valuation rather than before, so it's not clear to me which is better. That said, if you are performing valuation, you probably already know which currency you're going to get, in most cases.

Thoughts?

**Comment by simonmichael** [comment] 2021-07-23 07:41
i'm not sure which is better behaviour either. I'll test a bit with both. 

Even if we decide to keep the new behaviour, I'm inclined to call this a regression since we didn't document it and it broke at least one user's reports. So qualifies for the https://hledger.org/regressionbounty !

**Comment by julian-klode** [comment] 2021-07-23 07:51
I guess I definitely need at least a switch to revert to the old behavior, otherwise I'd have no way of knowing how much I hold of a given currency (which really are securities here). Otherwise I have to also run `hledger prices` and parse that output and calculate myself which is annoying :)

**Comment by simonmichael** [comment] 2021-07-23 08:43
There are some other ways (prefilter with print; match by account instead) but they are less accurate, so I hear that. 

That said, it can be a bit confusing for new and forgetful users when cur:, which normally reliably limits the currencies you see, sometimes appears not to do so.  

I wonder about keeping the new cur: behaviour and adding ocur: (match old/original currency) for the old. I can imagine use cases for both kinds of matching, though I'm not sure how important they are. This might be an unnecessary feature. Also it means a change in behaviour, affecting folks like Julian. 

I think this issue. won't come up much with other kinds of query - valuation changes what's being matched which causes the order of operations to matter, but this is unusual.

**Comment by simonmichael** [comment] 2021-07-23 08:50
Well. I guess the same thing arises with amt:, does it/should it match before or after valuation. Similarly, do we match account names before or after aliasing.

**Comment by julian-klode** [comment] 2021-07-23 09:32
I'm inconsistent too: `hledger --alias foo:bar bar` I expect to show `foo` too (I actually gather money in subaccounts for quarterly payments, but aliasing them to expenses for expense reporting makes more sense). 

For currency matching, I sort of expect it to match the currency in the file. It seems useless otherwise, the problem being that if I use --value all (most of) my currency will be reported in default currency.

There is also the evil approach where you make `cur:test -V` filter first and `-V cur:test` filter last (generally the same for other stuff). If the command line parser supports that - it might not. I guess we're limited by lack of a proper query language here, if it were `value:now . cur:test` and `cur:test . value:now` it would be obvious (using dot for "after" as in math)

**Comment by simonmichael** [comment] 2021-07-27 21:21
I have documented current behaviour at https://hledger.org/dev/hledger.html#querying-with-account-aliases

**Comment by simonmichael** [comment] 2021-07-27 21:39
1. The order of arguments idea is clever but too troublesome I think.

2. A full boolean query language has been on the wishlist for ever. Adding "order of matching" control to that seems.. unusual, but it's an idea.

3. My notion of separate query types for old and new commodity/amount is another.

4. We could make `cur:` and `amt:` match either old or new, like `acct:`. It sacrifices precision and might not work well in practice, since commodity symbols and amounts are less unique than account names. Would need some testing.

5. We could take the path of least resistance/least cost and revert to the 1.21 behaviour (matching the old commodity/amount). 

Are there use cases for matching the new commodity ? I think so, but they are less useful than matching the old one.

Are there use cases for matching the new amount ? I think this is something people try to do, perhaps more often than matching the new one. Maybe it's 50-50.

To save time, I would probably lean towards 3 until we see strong requests for change.

**Comment by simonmichael** [comment] 2021-07-27 21:39
Sorry, I meant 5.

**Comment by simonmichael** [comment] 2021-07-27 21:40
(Assuming restoring the old behaviour is not very costly to implement.)

**Comment by Xitian9** [comment] 2021-07-28 00:09
I would agree with reverting to matching pre-conversion currency. I have no idea whether matching pre- or post-conversion amount quantity is more convenient. I'll leave it as matching post-conversion for now, but let me know if you'd like that changed.

**Comment by Xitian9** [comment] 2021-07-28 00:12
Correction: I'll make it so we always match against pre-valuation postings. If you'd like that changed, let me know.

**Comment by simonmichael** [comment] 2021-07-30 19:08
Thanks to @Xitian9 for restoring the old behaviour (`cur:` and `amt:` match before valuation) in master. This will be in 1.22.1. We can revisit supporting post-valuation matching in future if there's need.

**Closed by simonmichael** 2021-07-30 19:08 UTC
Labels: A BUG, docs, queries, regression!, release-needed, valuation

**Comment by simonmichael** [comment] 2021-07-30 19:22
@julian-klode, would you like to claim the https://hledger.org/regressionbounty ? I encourage it, it's good to exercise the project finances and the bounty mechanisms.

**Comment by julian-klode** [comment] 2021-07-30 19:36
ack, invoiced.
