### ISSUE TITLE
command print removes some remarks

### ISSUE THREAD

**Issue by PSLLSP** [simonmichael/hledger#1938] opened 2022-10-04 01:01 UTC
hledger 1.27.1

Comments those are not part of statements are removed by command print. It means I cannot use print command to reformat my journal file because some comments will be lost... :-(

Example:
```
$ cat test.journal
# This is a demo journal to show that comments are removed with print command

; this is different comment that will be lost

comment
This is comment with several lines
this kind of remark is removed too :-(
end comment

2008/01/01 income     ; first line of statement
  ; second line of some important remark
  assets:bank:checking   $1   ; this is an account in the bank
  income:salary         $-1        ; received just one dollar!
  ; this is an additional information

; == start new year ==

2009-01-01 income
  assets:bank:checking              $2
  income:salary                    $-2
```

```
$ hledger --version
hledger 1.27.1, linux-x86_64

$ hledger -f test.journal print
2008-01-01 income  ; first line of statement
    ; second line of some important remark
    assets:bank:checking              $1  ; this is an account in the bank
    income:salary                    $-1  ; received just one dollar!
    ; this is an additional information

2009-01-01 income
    assets:bank:checking              $2
    income:salary                    $-2
```

I noticed that older hledger (1.12.1) prints dates in format YYYY/MM/DD, but version 1.27.1 prints them in format YYYY-MM-DD. I personally prefer YYYY-MM-DD format but I noticed that hledger parses such date as tag (during import from CSV file). I thought I will use print command to reformat my journal, and it will change date from YYYY-MM-DD to YYYY/MM/DD but this output was changed. Just a note, this is not an issue for me. Format YYYY-MM-DD is good, it is format from ISO 8601. This issue is about comments those are lost.

From my of point of view, comments should not be removed by print command. In some cases, these comments could be viewed as a noise and could be removed with some switch added to print command...

**Comment by the-solipsist** [comment] 2022-10-08 20:47
Seems like a duplicate of this feature request: https://github.com/simonmichael/hledger/issues/1880

**Comment by simonmichael** [comment] 2022-10-08 23:31
And https://github.com/simonmichael/hledger/issues/1127

**Closed** 2022-10-08 23:31 UTC
Labels: closed: duplicate, A WISH, print
