### ISSUE TITLE
performance regression in 1.19.1 ?

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1350] opened 2020-09-10 00:38 UTC
I see these kind of numbers with 1.19.1 - rough measurements, but suggesting a 3x slowdown:
```
$ BENCHEXES=hledger-1.18,hledger-1.19,hledger-1.19.1 make bench

run quick performance benchmarks in bench.sh (approximate, can be skewed):
quickbench -w hledger-1.18,hledger-1.19,hledger-1.19.1  # -v
Running 12 tests 1 times with 3 executables at 2020-09-09 17:26:16 PDT:

Best times:
+-----------------------------------------------++--------------+--------------+----------------+
|                                               || hledger-1.18 | hledger-1.19 | hledger-1.19.1 |
+===============================================++==============+==============+================+
| -f examples/100x100x10.journal print          ||         0.13 |         0.11 |           0.17 |
| -f examples/1000x1000x10.journal print        ||         0.39 |         0.27 |           1.08 |
| -f examples/10000x1000x10.journal print       ||         3.43 |         2.69 |           9.72 |
| -f examples/10000x1000x10.journal print ff    ||         1.42 |         1.48 |           4.73 |
| -f examples/100x100x10.journal register       ||         0.10 |         0.09 |           0.16 |
| -f examples/1000x1000x10.journal register     ||         0.42 |         0.42 |           1.10 |
| -f examples/10000x1000x10.journal register    ||         4.97 |         3.57 |          11.45 |
| -f examples/10000x1000x10.journal register ff ||         1.75 |         1.39 |           5.48 |
| -f examples/100x100x10.journal balance        ||         0.08 |         0.07 |           0.13 |
| -f examples/1000x1000x10.journal balance      ||         0.31 |         0.30 |           0.89 |
| -f examples/10000x1000x10.journal balance     ||         1.99 |         1.59 |           5.95 |
| -f examples/10000x1000x10.journal balance ff  ||         1.48 |         1.24 |           5.03 |
+-----------------------------------------------++--------------+--------------+----------------+

```

**Comment by simonmichael** [comment] 2020-09-10 19:34
It's harder to see the difference in the profiles, but notice the increased memory allocation and the appearance of stripAnsi as top cost center. It seems likely that https://github.com/simonmichael/hledger/commit/600dab3976cabfcaa4dfaedc67ebc6fd99d2a340 was a pessimisation.

[hledger-1.19-ghc883-prof.prof.txt](https://github.com/simonmichael/hledger/files/5204230/hledger-1.19-ghc883-prof.prof.txt)
[hledger-1.19.1-ghc884-prof.prof.txt](https://github.com/simonmichael/hledger/files/5204228/hledger-1.19.1-ghc884-prof.prof.txt)

Simplified:
[hledger-1.19-ghc883-prof.profiterole.txt](https://github.com/simonmichael/hledger/files/5204224/hledger-1.19-ghc883-prof.profiterole.txt)
[hledger-1.19.1-ghc884-prof.profiterole.txt](https://github.com/simonmichael/hledger/files/5204223/hledger-1.19.1-ghc884-prof.profiterole.txt)

**Comment by simonmichael** [comment] 2020-09-11 01:14
I've restored the regular expression-based implementation we had in 1.18, which fixes the slowdown:
```
+-----------------------------------------------++--------------+--------------+----------------+---------+
|                                               || hledger-1.18 | hledger-1.19 | hledger-1.19.1 | hledger |
+===============================================++==============+==============+================+=========+
| -f examples/100x100x10.journal print          ||         0.19 |         0.18 |           0.22 |    0.67 |
| -f examples/1000x1000x10.journal print        ||         0.29 |         0.25 |           0.89 |    0.27 |
| -f examples/10000x1000x10.journal print       ||         2.68 |         2.41 |           8.21 |    2.36 |
| -f examples/10000x1000x10.journal print ff    ||         1.07 |         1.05 |           4.26 |    1.11 |
| -f examples/100x100x10.journal register       ||         0.09 |         0.08 |           0.16 |    0.08 |
| -f examples/1000x1000x10.journal register     ||         0.33 |         0.28 |           0.94 |    0.30 |
| -f examples/10000x1000x10.journal register    ||         3.34 |         2.49 |           9.24 |    2.85 |
| -f examples/10000x1000x10.journal register ff ||         1.11 |         0.97 |           3.93 |    1.09 |
| -f examples/100x100x10.journal balance        ||         0.06 |         0.06 |           0.11 |    0.07 |
| -f examples/1000x1000x10.journal balance      ||         0.25 |         0.24 |           0.63 |    0.24 |
| -f examples/10000x1000x10.journal balance     ||         1.54 |         1.15 |           4.13 |    1.25 |
| -f examples/10000x1000x10.journal balance ff  ||         1.16 |         0.98 |           3.79 |    1.08 |
+-----------------------------------------------++--------------+--------------+----------------+---------+
```

I'll probably release this as 1.19.2 in the coming days, unless someone optimises again soon. @Xitian9 I left more notes on the reasoning and prospects for further improvement in f78dc63. As said there ideally we would not have to strip ANSI codes, I'm not sure how huge a refactoring that would require.

**Comment by simonmichael** [comment] 2020-09-11 01:15
PS there was some discussion of the parser's performance in today's #haskell log.

**Comment by Xitian9** [comment] 2020-09-11 01:28
Was it specifically 600dab3 that led to the regression? Was the previous (incorrect) code fast?

**Comment by simonmichael** [comment] 2020-09-11 01:34
Yes, and maybe (quickbench seemed to show hledger slightly faster, timeit in ghci shows the parser slower).

**Comment by Xitian9** [comment] 2020-09-11 01:38
In that case, it's most likely the use of `anySingle` instead of the previous `takeWhile1P`.

That said, I agree that getting rid of `stripAnsi` entirely would be a better solution. Let me put some thought into that.

**Comment by Xitian9** [comment] 2020-09-11 01:52
Just putting this here for reference http://hackage.haskell.org/package/strip-ansi-escape.

**Comment by simonmichael** [comment] 2020-09-11 16:37
We should measure how much this affects overall performance before spending a lot of effort of course, I haven't done that.

**Comment by Xitian9** [comment] 2020-11-02 01:41
Since `stripAnsi` is no longer called after #1354 , perhaps this issue can be closed now.

**Comment by simonmichael** [comment] 2020-11-04 04:15
This is still open because I did not release the fix, lamentably. Noone has complained, at this point I might just wait until 1.20 on dec 1.

**Comment by mhansen** [comment] 2020-11-28 01:44
Just to tie two discussions together, link to the mailing list, looks like this slowdown may have affected me: https://groups.google.com/g/hledger/c/l07h9g_cTgw/m/Y_S4K5eoAQAJ

**Comment by Xitian9** [comment] 2021-01-07 21:14
I think we can safely close this issue now.

**Closed** 2021-01-07 21:51 UTC
Labels: A BUG, performance
