### ISSUE TITLE
hledger print strange formatting issue

### ISSUE THREAD

**Issue by markokocic** [simonmichael/hledger#2152] opened 2024-01-11 10:45 UTC
I have the following directive at the beginning of the ledger file:

```
D -1,000,000.00 €
```

Later in the file, I have the following entry:
```
2014/07/03 Exchange to Rupies
    expenses:cash  1350 inr @@ 20
    expenses:cash
```
When I tried to print using `hledger print` command, I got the `inr` in the wrong format.
```
marko@fine ~/s/c/hledger (master)> hledger print | grep inr
    expenses:cash    1,350. inr @@ 20.00 €
```
Note the extra `.` at the end of the amount.

I was unable to isolate the issue by creating a test file, but it started happening in my real ledger file some time ago. I guess it may be affected by some other unrelated transaction entries before that, since the entry in case is the first entry with `inr` as a currency.

**Comment by simonmichael** [comment] 2024-01-11 19:28
I'm guessing you're using 1.31, which added that to disambiguate numbers ? 1.32 should fix it.

**Comment by simonmichael** [comment] 2024-01-11 19:30
Oh wait, no, it will still happen with `print`. 1.32 stopped it happening with other reports.

https://hledger.org/release-notes.html#hledger-131

> print no longer displays numbers with a single digit group mark and no decimal mark, which are ambiguous and hard to re-parse. Now if a number has digit group marks the decimal mark will always be shown also. Eg `1,000` (where the comma is a thousands separator) is now shown as `1,000.`.

**Comment by markokocic** [comment] 2024-01-11 19:31
I built it this morning from git
```
hledger --version
hledger 1.32.99-g80e4428e7-20240106, linux-x86_64
```

**Comment by simonmichael** [comment] 2024-01-11 19:31
(If it looks ugly, you can since 1.32 force extra decimal digits with `print --round=soft`)

**Comment by markokocic** [comment] 2024-01-12 10:39
Yes, this is a workaround, but I think this may still be a bug because the trailing dot is in my case displayed only for `inr`, and not for `€`, `rsd` or `$`

**Comment by simonmichael** [comment] 2024-01-12 16:55
I expect there's a logical reason - if you can provide a repro I'll check it.

**Comment by markokocic** [comment] 2024-01-15 11:35
hi @simonmichael , after some fiddling around, I managed to make a reproducible test:

``` shell
marko@fine ~> cat test2.journal
; -*- mode: ledger-*-

; Set default currency and format
D -1,000,000.00 €

2014/07/03 Exchange to Rupies
    expenses:cash  1350 inr @@ 20
    expenses:cash

2014/07/07 P1 ows to P2
    liabilities:p1  1200 inr
    liabilities:p2

2014/07/11=07/10 Hotel prepayment
    liabilities:travel  29,362.42 inr @@ 364.06
    liabilities:travel  5.46
    liabilities:cc
marko@fine ~>
```
As long as the file contains only first two transactions, print show all inr values in a normal format.

However, as soon as the third transaction is added to the file, all inr values are displayed with a trailing dot.

Other hledger commands like bal, bs, cf, inc seems to work fine.

**Comment by simonmichael** [comment] 2024-01-15 16:24
Thanks! Yes this is working as intended: 

- in the third txn you use a comma thousands mark
- so hledger infers that inr amounts should be displayed with comma thousands mark
- so the first two will be displayed as 1,350 inr and 1,200 inr
- but those are ambiguous and can't be parsed reliably; so it adds the period decimal mark to solve that
- by default, it does not add decimal zeros because that would imply more precision than was written
- with --round=soft, it adds the zeros.

I hope that makes sense. I need to document this.

**Comment by simonmichael** [comment] 2024-01-15 16:26
Actually it's documented here: https://hledger.org/dev/hledger.html#amount-formatting-parseability

I'll add a link at https://hledger.org/dev/hledger.html#commodity-styles

**Comment by markokocic** [comment] 2024-01-15 16:43
Thanks for the explanation.

I added the following declaration right after D to the previous example file:
```
commodity -1,000,000.00 inr
```

However, I would expect that now `€` and `inr` would be treated the same way. However, in this case `€` gets rounded with `.00` by default, while `inr` only with `.`

**Comment by simonmichael** [comment] 2024-01-15 17:01
As of recent versions, `print` doesn't add any decimal digits by default, even if the commodity display style specifies more. https://hledger.org/dev/hledger.html#print-amount-style ,  release notes tell more.

**Comment by markokocic** [comment] 2024-01-15 17:10
Ok, thanks.

I updated my hledger wrapper script to automatically add `--round=soft` to the print command. That solves the issue for me, though I still find it less intuitive than previous behaviour, since it differs from the default currency printing style, and since other commands except print do it "right" (by my defition of right :)

**Comment by simonmichael** [comment] 2024-01-15 17:37
I hear you.  But let me see if I can persuade you: 

 `print` is often used for reformatting journal entries or for exporting to other PTA tools; so unlike other reports it is expected to be re-parseable and as non-lossy as possible. When it used to add decimal digits for display, that often (not always) looked pretty but it altered the data - (a) implying more precision than was originally recorded, which might sometimes be undesirable, and (b) possibly changing precisions inferred from the journal, which could affect output and even transaction balancing. I think I had cases where rewriting entries with print caused the journal to stop balancing.

**Comment by simonmichael** [comment] 2024-01-15 17:40
So, now it is information-preserving by default, and the old behaviour requires adding `--round=soft`.  I know it's not nice when familiar behaviour is changed - sorry about that. I did call it out as a breaking change I think, and of course discussed it in advance.

**Comment by simonmichael** [comment] 2024-01-22 19:33
Ok to close this one I guess.

**Closed by simonmichael** 2024-01-22 19:33 UTC
Labels: docs, print
