### ISSUE TITLE
Unbalanced multi-commodity transaction after upgrading to `1.32.1`

### ISSUE THREAD

**Issue by stewmehr** [simonmichael/hledger#2135] opened 2023-12-10 21:31 UTC
Hi there,

I have trouble with a slightly modified/updated version of the transaction mentioned in #2057. The following ledger file

```
commodity 1,000.00 €
commodity 1,000.0000 "LYX0Q0"

2023-01-18=2023-01-16
     assets:stewmehr:bnp:giro                                       -304.0 €
     assets:stewmehr:bnp:depot:LYX0Q0:20230116    1.5111 "LYX0Q0" @ 200.65 €
     expenses:depot:gebuehren                                         0.80 €
```

used to cause no issues on my end until I recently upgraded `hledger`. It appears that the significant digits that are defined along with the commodities are no longer respected. I am well aware that the transaction is not balanced in a strict sense (there should be a difference of `-0,002215 €`) but as far as I can remember previous versions of `hledger` were able to "ignore" this numerical issue.

```
13 | 2023-01-18=2023-01-16
   |     assets:stewmehr:bnp:giro                                       -304.0 €
   |     assets:stewmehr:bnp:depot:LYX0Q0:20230116    1.5111 "LYX0Q0" @ 200.65 €
   |     expenses:depot:gebuehren                                         0.80 €

This multi-commodity transaction is unbalanced.
The real postings' sum should be 0 but is: 0
Consider adjusting this entry's amounts, adding missing postings,
or recording conversion price(s) with @, @@ or equity postings.
This multi-commodity transaction is unbalanced.
The real postings' sum should be 0 but is: 0
Consider adjusting this entry's amounts, adding missing postings,
or recording conversion price(s) with @, @@ or equity postings.
```

Version:
`hledger 1.32.1, mac-x86_64`

**Comment by simonmichael** [comment] 2023-12-13 01:40
The example above gives me a different error, because of the inconsistent decimal marks - could you update it ?
```
The real postings' sum should be 0 but is: 303199255 € 
```

**Comment by stewmehr** [comment] 2023-12-13 06:46
Oh no, I am sorry. Serves me right for manually adding the two lines at the top from memory instead of copying them from my journal files. I have updated the example.

**Comment by simonmichael** [comment] 2023-12-13 09:35
Can't reproduce yet.

**Comment by stewmehr** [comment] 2024-01-24 10:18
Hi @simonmichael,
sorry for not following up on this - I simply downgraded to a previous version of hledger and completely forgot about this minor annoyance. Will try and investigate this further on my end this week.

**Comment by simonmichael** [comment] 2024-02-02 17:44
Closing, let me know if it shows up again.

**Comment by stewmehr** [comment] 2024-02-05 08:07
My apologies, I finally had time to upgrade to `1.32.3` and the issue has reappeared. The transaction in question is the same as above.

**Comment by simonmichael** [comment] 2024-02-05 18:34
Hi @stewmehr, I must depend on you to show a way to reproduce this, since nobody else can. Are you sure that you are testing the exact test file at the top of this page, with no other data involved ? I'll reproduce it here for reference:
```
commodity 1,000.00 €
commodity 1,000.0000 "LYX0Q0"

2023-01-18=2023-01-16
     assets:stewmehr:bnp:giro                                       -304.0 €
     assets:stewmehr:bnp:depot:LYX0Q0:20230116    1.5111 "LYX0Q0" @ 200.65 €
     expenses:depot:gebuehren                                         0.80 €
```
```
$ cat > a.j
commodity 1,000.00 €
commodity 1,000.0000 "LYX0Q0"

2023-01-18=2023-01-16
     assets:stewmehr:bnp:giro                                       -304.0 €
     assets:stewmehr:bnp:depot:LYX0Q0:20230116    1.5111 "LYX0Q0" @ 200.65 €
     expenses:depot:gebuehren                                         0.80 €

$ hledger-1.32.3 --version
hledger 1.32.3-gcaeab172a-20240128, mac-aarch64
$ hledger-1.32.3 -f a.j print
2023-01-18=2023-01-16
    assets:stewmehr:bnp:giro                                       -304.0 €
    assets:stewmehr:bnp:depot:LYX0Q0:20230116    1.5111 "LYX0Q0" @ 200.65 €
    expenses:depot:gebuehren                                         0.80 €

$ hledger-1.32.3 -f a.j stats
Main file                : /Users/simon/src/hledger/a.j
Included files           : 
Transactions span        : 2023-01-16 to 2023-01-19 (3 days)
Last transaction         : 2023-01-18 (383 days ago)
Transactions             : 1 (0.3 per day)
Transactions last 30 days: 0 (0.0 per day)
Transactions last 7 days : 0 (0.0 per day)
Payees/descriptions      : 1
Accounts                 : 3 (depth 6)
Commodities              : 2 (LYX0Q0, €)
Market prices            : 0 ()

Run time (throughput)    : 0.07s (15 txns/s)
```

**Comment by stewmehr** [comment] 2024-02-05 20:47
Hi @simonmichael,
Thank you for your patience. I have been able to confirm that the single transaction in question does indeed *not* crash. Rather, it seems that another transaction further down in my journal was causing issues and I simply relied too much on the info in the crash log. 

I have played around with my journals and believe that I can now narrow my issue down to a bug that occurs when passing multiple files to hledger.

Can you please try to reproduce the following example?

`a.j`
```
2023-01-18=2023-01-16 * LU0908500753 LY.I.-L.CO.ST. EO 600(DR)A  ; Wertpapierkauf
    assets:stewmehr:bnp:giro                                       -304.0 €
    assets:stewmehr:bnp:depot:LYX0Q0:20230116    1.5111 "LYX0Q0" @ 200.65 €
    expenses:depot:gebuehren                                         0.80 €

2023-01-30=2023-01-26 * US88160R1014 TESLA INC. DL  -,001  ; Wertpapierverkauf
    assets:stewmehr:bnp:giro                                      1,709.6 €
    assets:stewmehr:bnp:depot:A1CX3T:20210412      -6 "A1CX3T" @ 193.5333 €
    assets:stewmehr:bnp:depot:A1CX3T:20210512        -6 "A1CX3T" @ 165.00 €
    expenses:depot:gebuehren                                         4.00 €
    expenses:depot:verluste                                      437.5998 €
```

`d.j`
```
commodity 1,000.00 €
commodity 1,000.0000 "A1CX3T"
commodity 1,000.0000 "LYX0Q0"
```

This is what happens on my end:

```
hledger -f d.j -f a.j print
hledger: Error: /Users/stewmehr/tmp/a.j:5-8:
5 | 2023-01-18=2023-01-16 * LU0908500753 LY.I.-L.CO.ST. EO 600(DR)A  ; Wertpapierkauf
  |     assets:stewmehr:bnp:giro                                       -304.0 €
  |     assets:stewmehr:bnp:depot:LYX0Q0:20230116    1.5111 "LYX0Q0" @ 200.65 €
  |     expenses:depot:gebuehren                                         0.80 €

This multi-commodity transaction is unbalanced.
The real postings' sum should be 0 but is: 0
Consider adjusting this entry's amounts, adding missing postings,
or recording conversion price(s) with @, @@ or equity postings.
```

Interestingly enough, copying and pasting the contents of `d.j` to the top of `a.j` resolves the issue on my end.

**Comment by simonmichael** [comment] 2024-02-05 22:07
Great! I can reproduce, thanks.

Here are some notes for the record (including things you may know already).
With a slightly simplified example, 

```
# e.j

#commodity 1,000.00 €

2023-01-18
    assets:stewmehr:bnp:giro                                       -304.0 €
    assets:stewmehr:bnp:depot:LYX0Q0:20230116    1.5111 "LYX0Q0" @ 200.65 €
    expenses:depot:gebuehren                                         0.80 €

2023-01-30
    assets:stewmehr:bnp:giro                                      1,709.6 €
    assets:stewmehr:bnp:depot:A1CX3T:20210412      -6 "A1CX3T" @ 193.5333 €
    assets:stewmehr:bnp:depot:A1CX3T:20210512        -6 "A1CX3T" @ 165.00 €
    expenses:depot:gebuehren                                         4.00 €
    expenses:depot:verluste                                      437.5998 €

```

The first transaction fails to balance (unless the commodity declaration is uncommented):

```
$ hledger -f e.j print
hledger: Error: /Users/simon/src/hledger/2024-02-05/e.j:5-8:
5 | 2023-01-18
  |     assets:stewmehr:bnp:giro                                       -304.0 €
  |     assets:stewmehr:bnp:depot:LYX0Q0:20230116    1.5111 "LYX0Q0" @ 200.65 €
  |     expenses:depot:gebuehren                                         0.80 €

This multi-commodity transaction is unbalanced.
The real postings' sum should be 0 but is: 0
Consider adjusting this entry's amounts, adding missing postings,
or recording conversion price(s) with @, @@ or equity postings.
```

This is normal; it means the entry is too inexact for the inferred precisions.

Explanation: transaction balancing allows some imprecision, guided by the commodities' display precisions.
In the above,
```
1.5111 * 200.65 = 303.202215
   304 - 0.80   = 303.20
```

These agree to two decimal places.
Most of your euro amounts have two decimal places.
`@ 193.5333  €` has four, but is a cost amount so doesn't affect inferred precisions.
But `437.5998 €` in the second transaction does, increasing euro's inferred precision to four decimal places (for display and for transaction balancing).

You can fix this by any of

- making the cost (200.65) more precise until it balances (doing this while watching with watchexec or flycheck-hledger or hledger-ui -w is convenient)
- reducing the precision of over-precise amounts, so the desired precision is inferred
- limiting the commodity's precision with a `commodity` directive.

I think you tried to do the last, but your commodity directive was in a separate (sibling) file and did not affect this file.
And this seems contrary to https://hledger.org/dev/hledger.html#directive-effects ,
which says that a declared commodity display/balancing precision does not stop at end of file.

Things we could do:

- Transaction balancing probably needs to be made clearer in the manual.
- The "real postings' sum should be 0 but is: 0" message was unhelpful; it should show more precision.
- Check/fix the `commodity` directive description in the Directive effects doc.
- #1964 is a place to discuss alternate transaction-balancing behaviour.

**Comment by simonmichael** [comment] 2024-02-05 22:41
I see the error message used to be more precise: in 1.30 it said
```
The real postings' sum should be 0 but is: 0.0022 €
```
but since 1.31 it says
```
The real postings' sum should be 0 but is: 0
```
which is perhaps a (small) regression.

**Comment by simonmichael** [comment] 2024-03-01 03:01
I pushed to master:
- a fix to show the imbalance more precisely in unbalanced transaction errors
- a new https://hledger.org/dev/hledger.html#transaction-balancing section
- fixes for the scopes of `commodity` directive's effects at https://hledger.org/dev/hledger.html#directive-effects and https://hledger.org/dev/hledger.html#commodity-directive

Which I believe resolves this issue.

**Comment by simonmichael** [comment] 2024-03-01 05:24
And, added notes to Transaction balancing and commodity directive sections about the directive's scope, since this can be surprising (I wasn't aware of it).

**Closed by simonmichael** 2024-03-01 05:24 UTC
Labels: A-BUG, docs, journal, severity2, impact4
