### ISSUE TITLE
CSV Import rule patterns break with commas

### ISSUE THREAD

**Issue by chrislloyd** [simonmichael/hledger#1053] opened 2019-06-15 21:30 UTC
Hi folks! I just found a fairly tricky case with the CSV import rules where commas in the original source line can break some patterns. Let me show you an example. I have an import rules file to help import transactions from Mint's CSV export:

```
if ^[^,]*,[^,]*,[^,]*,[^,]*,debit
  amount -%amount
```

(I can't remember exactly where I found that style, IIRC it was somewhere fairly official) This worked really well until I discovered that I actually ended up running a negative coffee expense. While I would love to get paid to drink coffee, it seemed like a bug. Tracing it down, I found that quite a few transactions were getting imported with their amount flipped. An example of one such transaction:

```
"1/1/2019","BLUE BOTTLE COFFEE, INC","BLUE BOTTLE COFFEE, INC","10.00","debit","Coffee Shops","CREDIT CARD","",""
```

I realized that the `,` in "Blue Bottle Coffee, Inc" was causing hledger to incorrectly apply the pattern. I changed the pattern to:

```
if ^"[^"]*","[^"]*","[^"]*","[^"]*","debit"
  amount -%amount
```

However this fails to match any transaction. Digging into Hledger a bit, I believe this is caused by [this line](https://github.com/simonmichael/hledger/blob/master/hledger-lib/Hledger/Read/CsvReader.hs#L851) in `CsvReader.hs` which takes the parsed CSV record, intercalculates it with "," and then applies the pattern against that. When a column contains a comma, that will produce a different result (with more columns) than the original CSV itself.

One solution would to be to change that line to something like (and I don't write haskell so please forgive me if this is wrong):

```hs
csvline = "\"" ++ (intercalate "\",\"" record) ++ "\""
```

However that will break some existing rulesfiles that match on the `,` character. Another fix would be to have the pattern match on the raw string line (and not try and reconstitute line from the already parsed record). I like this option better because I think matching against the CSV source the user gives hledger is more intuitive that matching against hledger's version. However, that would require a little more re-jigging than I feel comfortable doing especially seeing as it would be a breaking change.

I'm not quite sure how to proceed but in the meantime I am just trying to detect cols with commas before I import with hledger (`grep "[^\"],[^\"]"`) and then fixing manually. Thanks for your help!

(Hledger 1.14.2)

**Comment by chrislloyd** [comment] 2019-06-15 21:42
Ha, just reading through the issues this seems worth considering in context of #1051.

**Comment by simonmichael** [comment] 2019-06-16 01:32
Thanks for the report. Your analysis could be right, but are you sure it's not that the double quotes are already gone from the content your regexp sees ? That's how I remember it.

Bottom line, this way of selecting fields by regexp is a kludge until somebody implements `if specificfield ~ debit`. I don't think I see a bug here, as hledger is working according to current spec. Probably I would kludge it more, by doing `if ,debit,` or something.

**Comment by simonmichael** [comment] 2019-07-08 05:12
I'll close this, unless you still think there's a bug here.

**Comment by alerque** [comment] 2019-07-08 06:48
I've done some pretty complicated expressions like this recently and ran into the same issue. But I'm also pretty sure there is not a bug here, it's just a matter of writing proper RegEx kludges. A feature request to match fields would be a super high priority in my book, but I don't see any reason for this bug report to be open because it's exactly as expected given the scenario.

**Comment by alerque** [comment] 2019-07-08 06:50
P.S. One way to mitigate this and keep your fields in alignment is to match on more than just the commas. If you know your amounts end in digits, match that. If all your payees start with letters, match that. Sometimes it only takes one extra bit of a field like that matching to avoid stray commas in payees and descriptions and match on what you think you're matching.

**Closed** 2019-07-08 07:44 UTC
Labels: A BUG, csv
