### ISSUE TITLE
Support balance resetting

### ISSUE THREAD

**Issue by mathstuf** [simonmichael/hledger#288] opened 2015-10-11 03:29 UTC
Ledger support is here:

http://ledger-cli.org/3.0/doc/ledger3.html#Resetting-a-balance

I would like to use this for other things (will post to the list).

Related to #258.

**Comment by simonmichael** [comment] 2015-10-11 04:00
#129 may have some code to salvage

**Comment by simonmichael** [comment] 2015-11-15 06:53
Duplicate of #157.

**Closed by simonmichael** 2015-11-15 06:53 UTC
Labels: duplicate, journal, WISH
