### ISSUE TITLE
Too many decimals or too long commodity name blanks out balance statement

### ISSUE THREAD

**Issue by jblachly** [simonmichael/hledger#1549] opened 2021-05-01 21:35 UTC
The combined length of the quantity and the commodity symbol can trigger a bug: If the length of quantity plus length of commodity symbol are longer than some maximum, the balance sheet report shows as empty:

```
; Populate the account with 2 different commodities
; The final entry will "zero" it out in balance statements

2021-01-01 * A first entry
    assets  99 REDBALLOONS
    income

2021-01-02 * A second entry
    assets  1.123456789012 GREENBALLOONS
    income
```

This is OK:
```
$ hledger -f /tmp/decimals.hledger bal
1.123456789012 GREENBALLOONS
              99 REDBALLOONS  assets
-1.123456789012 GREENBALLOONS
              -99 REDBALLOONS  income
--------------------
                   0
```

This is not:
```
$ hledger -f /tmp/decimals.hledger bs
Balance Sheet 2021-01-03

             || 2021-01-03
=============++============
 Assets      ||
-------------++------------
 assets      ||
-------------++------------
             ||
=============++============
 Liabilities ||
-------------++------------
-------------++------------
             ||
=============++============
 Net:        ||
```

I can resolve this by EITHER shortening up the number of decimals in the quantity of green balloons, OR truncating the commodity symbol name:

`1.123456789012 GREENBA` or `1.123456 GREENBALLOONS` are the respective maximum printables, **if there are other commodities also to display**. Thus it seems like the maximum is a result of quantity length, commodity name length, and the text , `N more.."

As a final experiment, I verified that commodities are shown in alphabetical order; as long as the offending long commodity is not listed first alphabetically, the bug does not manifest.

Finally, this does not seem to be affected by my terminal width.

Kind regards

**Comment by Xitian9** [comment] 2021-05-03 00:47
Thanks @jblachly! This looks like it might be a duplicate of #1526; if it is, then it should be fixed in master and will be in the next bugfix release. If you are able to build from master, you could check it out and see if it resolves your issue.

**Comment by simonmichael** [comment] 2021-07-01 02:08
Yes thanks for the report, this seems to be already resolved.

**Closed by simonmichael** 2021-07-01 02:08 UTC
Labels: A BUG, regression!
