### ISSUE TITLE
Piping text output to 'head' yields error

### ISSUE THREAD

**Issue by thielema** [simonmichael/hledger#2272] opened 2024-10-21 08:55 UTC
~~~~
$ hledger -f hledger-journal register Foobar | head
...
hledger: user error (Pager exited with exit code 141

)
~~~~

I guess this has something to do with the new pager.

**Comment by simonmichael** [comment] 2024-10-24 20:55
For me on mac the error looks like "hledger: fd:14: hPutBuf: resource vanished (Broken pipe)". I'm assuming it's the same.

Confirmed that `hledger register --pager=no | head` does not give the error.

Just quitting the pager with `q` also produces the error, for any report output (but not help output). (Wonder why I didn't notice this.)

**Comment by simonmichael** [comment] 2024-10-25 04:02
I think the pager lib has buggy conduit code. Here's a repro: https://github.com/pharpend/pager/issues/4

**Comment by simonmichael** [comment] 2024-10-25 04:03
(The error appears only with output larger than ~80K or so, and/or above a certain number of lines.)

**Comment by simonmichael** [comment] 2024-11-01 05:23
Actually the problem was this: when piping in the input via stdin, if the pager quits (before reading all of it, perhaps), the process that's writing to the pipe gets an EPIPE IO error. I have pushed a fix, and a new hopefully quite robust pager runner.

I have also pushed, and perhaps this should have been a new PR, a bunch of extra options for a nice experience when using `less`:

```
--chop-long-lines
--hilite-unread
--ignore-case
--mouse
--no-init
--quit-at-eof
--quit-if-one-screen
--RAW-CONTROL-CHARS
--shift=8
--squeeze-blank-lines
--use-backslash
--use-color
```

These are appended to the user's LESS and MORE vars (less uses the latter when emulating MORE), overriding any settings there. This is probably over ambitious and GNU/Linux-centric, and may need refinement, so all testing is welcome.

**Closed** 2024-11-01 05:38 UTC
Labels: A-BUG, web, cli, ui

**Comment by lestephane** [comment] 2025-01-05 13:20
It looks like `--use-color` is not supported by the `less` version in dastapov/hledger:1.41.

```shell
$ /usr/bin/hledger print something
There is no use-color option ("less --help" for help)
$ less --version
less 551 (GNU regular expressions)
Copyright (C) 1984-2019  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: http://www.greenwoodsoftware.com/less
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
...
```

my workaround is

```shell
HLEDGER_LESS='' /usr/bin/hledger print something
```

I export the HLEDGER_LESS='' in .my .envrc and call it a day.
But this might be confusing to other users at first.

**Comment by adept** [comment] 2025-01-05 13:37
@lestephane thank you for the report, i will bump the OS container version

**Comment by adept** [comment] 2025-01-05 16:15
I've rebuilt docker image with newer debian, `less` there should support `--use-color`
