### ISSUE TITLE
stack.yaml.lock files

### ISSUE THREAD

**Issue by legrostdg** [simonmichael/hledger#1230] opened 2020-04-20 15:49 UTC
Should new `stack.yaml.lock` files be added to git or to .gitignore, that is the question.

**Comment by alerque** [comment] 2020-04-20 20:44
The [docs disagree](https://docs.haskellstack.org/en/stable/lock_files/) here, lock files should be committed:

> These files can be stored in source control

This is pretty standard for Applications that use lock files where the goal of the lock file is to enable reproducible builds in an ecosystem with ever changing dependency availability. Exact specifics vary by language but very generally _libraries_ can get away without lock files being tracked in version control, _applications_ generally should track them.

I'm not enough to of a Haskell expert to know if there are special considerations for this case, but that's the general lay of things.

**Comment by simonmichael** [comment] 2020-04-20 23:03
Thanks, that's a great doc. 

Lock files have their place, but I'm still not sure they are worth the trouble for us. There is one per stack yaml file. We have 6 of those, of which stack.yaml is the most important. It is used by 1. power users installing the latest master from source and 2. hledger contributors/developers. Since I test it pretty frequently, I feel stack builds without a preexisting lock file are pretty reliable for both of those groups. If we start committing lock files, I fear creating lots of busywork dealing with unnecessary commits and merge conflicts, just as already happens with the cabal files.

**Comment by alerque** [comment] 2020-04-20 23:09
You may be right, you're speaking from experience with Haskell & this app in particular. I was checking the docs because what I know from other projects didn't match and I was curious. I don't build this project often enough to have a feel for how stable or unstable the dependencies make the build process. If it's virtually never a problem then the lock files might be more trouble than they are worth.

**Comment by Xitian9** [comment] 2021-09-09 23:09
So is the current situation fine then? Perhaps we can close this issue.

**Comment by simonmichael** [comment] 2021-09-09 23:18
I think so. When this causes an actual problem we could reconsider.

**Closed by simonmichael** 2021-09-09 23:18 UTC
Labels: tools
