### ISSUE TITLE
1.32+: inaccurate value reports caused by low precision P amounts

### ISSUE THREAD

**Issue by akanshaG42** [simonmichael/hledger#2254] opened 2024-10-05 17:33 UTC
Hi, seems like transactions are not balances with multiple commodities, potentially due to rounding issue.

b.journal
```
D R1,23,45,678.0 ; defualt currency of R

P 2023-09-15 USD 83.1 ; USD to R on 09/15

2023-09-15
    assets:equity:acme    66 acme @ 10.2 USD
    income:acme:rsu
```

Now if I want to see the balance in R, as per docs I will have to pass the  and `--infer-market-prices` and `--value=then,R` so that purchase/cost price is used.

```
$ ~/Downloads/hledger-linux-x64/hledger -f b.journal bal   --infer-market-prices --value=then,R

           R55,941.6  assets:equity:acme
          R-55,942.9  income:salary:acme
--------------------
               R-1.3
```

The -1.3 seems unexpected. The posting are completely balanced if I use round numbers.

b.journal

```
D R1,23,45,678.0 ; defualt currency of R

P 2023-09-15 USD 83 ; USD to R on 09/15

2023-09-15
    assets:equity:acme    66 acme @ 10 USD
    income:salary:acme
```

```
$ ~/Downloads/hledger-linux-x64/hledger -f b.journal bal  --infer-market-prices --value=then,R

           R54,780.0  assets:equity:acme
          R-54,780.0  income:salary:acme
--------------------
                   0
```

I have  gone through the manual sections of Cost and Value reporting as well as the Track Investments cookbook multiple time and seems like the command line flags are correct. 

Though I have been using hledger for many years, this is the first time I have to deal with foreign stocks and equity, so it is completely possible that I am doing something wrong. 

Would appreciate any help.

Thanks!

**Version Info**
```
$ ~/Downloads/hledger-linux-x64/hledger --version

hledger 1.40, linux-x86_64
```

**Comment by simonmichael** [comment] 2024-10-06 02:29
Hi @akanshaG42, thanks for the report. I must admit I'm not seeing an explanation just yet!

Here's a simpler example:

```
P 2023-09-15 USD R90.0

2023-09-15
    assets    50 acme @ 10.0 USD
    income
```
The postings will have the same cost (by definition), and if valued with the same market prices, should also have the same value:
```
$ hledger print -X R --infer-market-prices
2023-09-15
    assets          R45000
    income         R-45000
```

But if I give both price and cost some non-zero decimal digits, the posting values diverge:

```
P 2023-09-15 USD R90.2

2023-09-15
    assets    50 acme @ 10.2 USD
    income
```
```
$ hledger -f b.j print -X R --infer-market-prices
2023-09-15
    assets          R46000
    income         R-46002

```

**Comment by simonmichael** [comment] 2024-10-06 04:48
A simpler case:
```
P 2000-01-01 USD R 100.5

2000-01-01
    (a)    50 ACME @ 10.5 USD
```

And it turns out to be a regression, since hledger 1.32:
```
$ hledger-1.31 print --infer-market-prices -X R
2000-01-01
    (a)       R 52762.5

$ hledger-1.32 print --infer-market-prices -X R
2000-01-01
    (a)         R 52760

```

During the chain of (two) conversions, an intermediate value is inappropriately rounded to the precision of the P directive's amount (one decimal place), causing inaccuracy. 

You can work around it for now by making sure P amounts have enough decimal digits. Eg for this example, changing it to `P 2000-01-01 USD R 100.50` makes the problem go away.

Thank you @akanshaG42! Please claim your https://hledger.org/REGRESSIONS.html#regression-bounty when convenient.

**Comment by simonmichael** [comment] 2024-10-06 08:33
This is fixed in master. 
(Linux x64 binary [here](https://github.com/simonmichael/hledger/actions/runs/11200346309) if it helps.)

**Comment by akanshaG42** [comment] 2024-10-06 10:17
Thank you for an incredibly fast turn around here @simonmichael. I tried the CI build with my actual ledger and it is balanced now. Thanks again!

**Comment by simonmichael** [comment] 2024-10-09 07:31
Hi @akanshaG42, I encourage you to claim your $50 regression finder's bounty within the next 7 days! If not, it will be recorded as a project donation.
https://hledger.org/REGRESSIONS.html#regression-bounty

**Comment by akanshaG42** [comment] 2024-10-09 15:39
> Hi @akanshaG42, I encourage you to claim your $50 regression finder's bounty within the next 7 days! If not, it will be recorded as a project donation. https://hledger.org/REGRESSIONS.html#regression-bounty

That's alright @simonmichael. Please consider it as a project donation.

**Closed** 2024-10-11 08:02 UTC
Labels: A-BUG, journal, valuation, regression
