### ISSUE TITLE
--forecast with end date is ending 2 days before end date rather than the day before

### ISSUE THREAD

**Issue by insanerwayner** [simonmichael/hledger#1711] opened 2021-09-22 00:00 UTC
_forecast.ledger_
```
~ daily  transaction
    (x)  1
```

_forecast command with end date_
```
hledger -f forecast.ledger reg --forecast -e "2021-09-25"
2021-09-21 transaction       (x)                          1             1
2021-09-22 transaction       (x)                          1             2
2021-09-23 transaction       (x)                          1             3
```
I'm expecting the last transaction displayed to be on the 2021-09-24.

This does give the desired result:
```hledger -f forecast.ledger reg --forecast="until 2021-09-25"```

**Comment by Xitian9** [comment] 2021-09-22 00:57
Thanks for the report! I think this is a duplicate of #1633, and it should be fixed in the upcoming release.

**Closed** 2021-09-22 08:18 UTC
Labels: A BUG, closed: duplicate, journal
